Feature/134209535/group chat
andela/kissa-cfh-project pull request #53
Opened 2016-12-13 21:45 UTC by andela-tisrael

#### What does this PR do?
Integrates chat application with the existing gaming User Inteface
#### Description of Task to be completed?
GIVEN I am a user
WHEN I am in a game
THEN I can send messages to other users and view sent and received messages in a public chat window
#### How should this be manually tested?
This can be manually tested when a user is about to start a game and opens the chat docker to participate in the chat session
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#134209535 Users should be able to chat with the group while they are in a game
#### Screenshots (if appropriate)
![screen shot 2016-12-13 at 10 39 26 pm](https://cloud.githubusercontent.com/assets/19914657/21160634/d7a5909a-c185-11e6-82bb-1efcb068746d.png)
![screen shot 2016-12-13 at 10 39 52 pm](https://cloud.githubusercontent.com/assets/19914657/21160635/d7a71bcc-c185-11e6-93b9-0593d7edc991.png)

#### Questions:

2016-12-15 23:32 UTC, mfalade commented on public/css/style.css
> +    /*height: 415px;*/
Feel free to yank this line out

2016-12-15 23:57 UTC, mfalade requested changes
Please address comments

2016-12-15 23:57 UTC, mfalade commented on public/css/style.css
> +    border:2px solid black;
As discussed, use Hex value instead of color name 

Read more in this Stack Overflow post.

[http://stackoverflow.com/questions/11620719/efficiency-of-color-selection-in-html-rgb-vs-hex-vs-name](http://stackoverflow.com/questions/11620719/efficiency-of-color-selection-in-html-rgb-vs-hex-vs-name)

2016-12-15 23:57 UTC, mfalade commented on public/css/style.css
> +  background: white;
Use Hex value here

2016-12-15 23:57 UTC, mfalade commented on public/js/controllers/game.js
> +    $scope.showChat = function () {
Do you want to rename this method to `toggleChatWindow` ? 

I believe that is more expressive.

2016-12-15 23:57 UTC, mfalade commented on public/js/services/chat.js
> +      showHide() {
Looks like `toggle` is the name you are looking for here.

Nice work adding a comment below.

2016-12-15 23:57 UTC, mfalade commented on public/js/services/game.js
>      if (data.round !== game.round && data.state !== 'awaiting players' &&
Declare a variable to hold the states you are looking out for like this. 
```javascript
const undesiredGameStates = ['awaiting players', 'game ended', 'game dissolved'];

if(data.round !== game.round && !undesiredGameStates.includes(data.round))
```

The advantage of doing this is that it makes it easier to manage/maintain the conditions

2016-12-15 23:57 UTC, mfalade commented on public/views/chat.html
> +        <i class="fa fa-2x fa-chevron-up minimize" ng-click="chat.showHide()" ng-hide="chat.isHidden" aria-hidden="true"></i>
I see what you did there 😉 

You can avoid the repetition still by doing this.

```html
<i  
  class="fa fa-2x minimize {{chat.isHidden ? 'fa-chevron-up' : 'fa-chevron-down'}}" 
  ng-click="chat.showHide()" 
  aria-hidden="true">
</i>
```

2016-12-16 08:14 UTC, andela-tisrael commented on public/views/chat.html
> +        <i class="fa fa-2x fa-chevron-up minimize" ng-click="chat.showHide()" ng-hide="chat.isHidden" aria-hidden="true"></i>
😀  thanks....on it

2016-12-16 08:15 UTC, andela-tisrael commented on public/js/services/chat.js
> +      showHide() {
done 👍

2016-12-19 15:49 UTC, andela-tisrael commented
PR closed as the task done does not match what was asked on pivotal tracker

2016-12-19 15:49 UTC, closed without merging